name: "Integrate Release"
# Integrate release runs in the base repo when it receives a pull request
on:
  pull_request_target:
    branches: [ main ]
    types: [opened, reopened]

jobs:
  call-workflow:
    uses: fair-ground/Fair/.github/workflows/integrate_release.yml@main
